apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aoaichatapp
  name: aoaichatapp
  namespace: azureai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aoaichatapp
  template:
    metadata:
      labels:
        app: aoaichatapp
    spec:
      containers:
      - image: mycontainerregistry66js.azurecr.io/aoaichatapp:latest
        name: aoaichatapp
        ports:
        - containerPort: 80
        resources: {}
